=== MFaheemRajput/Json-Schema-validation/json_schema/src/main/resources/person-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Person",
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "minLength": 3,
        "maxLength": 50
      },
      "age": {
        "type": "integer",
        "minimum": 0,
        "maximum": 120
      },
      "email": {
        "type": "string",
        "format": "email",
        "pattern": "^[a-zA-Z0-9._%+-]+@example\\.com$"
      },
      "isEmployed": {
        "type": "boolean"
      }
    },
    "required": ["name", "age"],
    "additionalProperties": false
  }

=== MFaheemRajput/Json-Schema-validation/json_schema/src/main/resources/persons.json
[
    {
      "name": "Alice",
      "age": 25,
      "email": "alice@example.com",
      "isEmployed": true
    },
    {
        "name": "Alex",
        "age": 25,
        "email": "Alexexample.com",
        "isEmployed": true
      },
    {
      "name": "Bob",
      "age": -1,
      "email": "bob@example.com",
      "isEmployed": false
    }
  ]
